/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/benchmark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Benchmark */
        get: operations["get_benchmark_api_benchmark_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dataset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dataset */
        get: operations["get_dataset_api_dataset_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Live Snapshot */
        get: operations["get_live_snapshot_api_live_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Live */
        get: operations["stream_live_api_live_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overview */
        get: operations["get_overview_api_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pr-checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pr Checks */
        get: operations["list_pr_checks_api_pr_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pr-checks/{check_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pr Check Detail */
        get: operations["get_pr_check_detail_api_pr_checks__check_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Detail */
        get: operations["get_run_detail_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/reruns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Reruns */
        get: operations["get_reruns_api_runs__run_id__reruns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/reruns/{rerun_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rerun Steps */
        get: operations["get_rerun_steps_api_runs__run_id__reruns__rerun_id__steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/steps/{step_idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Step Payload */
        get: operations["get_step_payload_api_runs__run_id__steps__step_idx__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/steps/{step_idx}/intervention-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Intervention Diff */
        get: operations["get_intervention_diff_api_runs__run_id__steps__step_idx__intervention_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/steps/{step_idx}/state-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get State Diff */
        get: operations["get_state_diff_api_runs__run_id__steps__step_idx__state_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AblationArm */
        AblationArm: {
            accuracy: components["schemas"]["CiValue"];
            /**
             * Name
             * @enum {string}
             */
            name: "snapshot" | "no_snapshot";
        };
        /** ArmResultView */
        ArmResultView: {
            /** N */
            n: number;
            /** Successes */
            successes: number;
        };
        /** BenchmarkSummary */
        BenchmarkSummary: {
            /** By Position */
            by_position: components["schemas"]["PositionAccuracy"][];
            /** Cost Histogram */
            cost_histogram: components["schemas"]["CostBucket"][];
            flaky_ablation: components["schemas"]["FlakyAblation"];
            /** Heatmap */
            heatmap: components["schemas"]["HeatmapCell"][];
            /** Methods */
            methods: components["schemas"]["MethodResult"][];
            /** Sankey */
            sankey: components["schemas"]["SankeyFlow"][];
        };
        /**
         * BlameCell
         * @description One cell of a run's blame stripe. `effect` is `None` for an untested step.
         */
        BlameCell: {
            /** Effect */
            effect: number | null;
            /** Step Idx */
            step_idx: number;
            /** Tested */
            tested: boolean;
        };
        /** BudgetStatus */
        BudgetStatus: {
            /** Cap */
            cap: number | null;
            /** Used */
            used: number;
        };
        /** CallsPoint */
        CallsPoint: {
            /** Calls Per Minute */
            calls_per_minute: number;
            /** Model */
            model: string;
            /** Ts */
            ts: string;
        };
        /**
         * CiValue
         * @description A point estimate with its 95% bootstrap CI. An estimate never appears without one.
         */
        CiValue: {
            /** Ci High */
            ci_high: number;
            /** Ci Low */
            ci_low: number;
            /** Value */
            value: number;
        };
        /** CostAccuracyPoint */
        CostAccuracyPoint: {
            /** Accuracy */
            accuracy: number;
            /** Mean Cost Usd */
            mean_cost_usd: number;
            /**
             * Method
             * @enum {string}
             */
            method: "bisect" | "judge_all_at_once" | "judge_step_by_step" | "rerun_live" | "no_control";
        };
        /** CostBucket */
        CostBucket: {
            /** Calls High */
            calls_high: number;
            /** Calls Low */
            calls_low: number;
            /** Count */
            count: number;
        };
        /** DatasetEntry */
        DatasetEntry: {
            /** Base Pass Rate */
            base_pass_rate: number;
            /** Domain */
            domain: string;
            /**
             * Fault Type
             * @enum {string}
             */
            fault_type: "wrong_value" | "missing_field" | "stale_record" | "tool_error";
            /** Faulted Pass Rate */
            faulted_pass_rate: number;
            /** Planted Step */
            planted_step: number;
            /**
             * Position Bucket
             * @enum {string}
             */
            position_bucket: "early" | "middle" | "late";
            /** Run Id */
            run_id: string;
            /**
             * Split
             * @enum {string}
             */
            split: "dev" | "test";
            /** Task Id */
            task_id: string;
        };
        /** DatasetPage */
        DatasetPage: {
            /** Entries */
            entries: components["schemas"]["DatasetEntry"][];
        };
        /** DiffEntry */
        DiffEntry: {
            /** After */
            after: string | null;
            /** Before */
            before: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "added" | "removed" | "changed";
            /** Path */
            path: string;
        };
        /** Envelope[HealthPayload] */
        Envelope_HealthPayload_: {
            data: components["schemas"]["HealthPayload"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[MetaPayload] */
        Envelope_MetaPayload_: {
            data: components["schemas"]["MetaPayload"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[RunDetail] */
        Envelope_RunDetail_: {
            data: components["schemas"]["RunDetail"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[SearchResults] */
        Envelope_SearchResults_: {
            data: components["schemas"]["SearchResults"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[StepPayload] */
        Envelope_StepPayload_: {
            data: components["schemas"]["StepPayload"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[BenchmarkSummary, NotAvailable]] */
        Envelope_Union_BenchmarkSummary__NotAvailable__: {
            /** Data */
            data: components["schemas"]["BenchmarkSummary"] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[DatasetPage, NotAvailable]] */
        Envelope_Union_DatasetPage__NotAvailable__: {
            /** Data */
            data: components["schemas"]["DatasetPage"] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[InterventionDiff, NoneType]] */
        Envelope_Union_InterventionDiff__NoneType__: {
            data: components["schemas"]["InterventionDiff"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[LiveSnapshot, NotAvailable]] */
        Envelope_Union_LiveSnapshot__NotAvailable__: {
            /** Data */
            data: components["schemas"]["LiveSnapshot"] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[OverviewPayload, NotAvailable]] */
        Envelope_Union_OverviewPayload__NotAvailable__: {
            /** Data */
            data: components["schemas"]["OverviewPayload"] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[PrCheckDetail, NotAvailable]] */
        Envelope_Union_PrCheckDetail__NotAvailable__: {
            /** Data */
            data: components["schemas"]["PrCheckDetail"] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[RerunPage, NotAvailable]] */
        Envelope_Union_RerunPage__NotAvailable__: {
            /** Data */
            data: components["schemas"]["RerunPage"] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[RunListPage, NotAvailable]] */
        Envelope_Union_RunListPage__NotAvailable__: {
            /** Data */
            data: components["schemas"]["RunListPage"] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[StateDiff, NotAvailable]] */
        Envelope_Union_StateDiff__NotAvailable__: {
            /** Data */
            data: components["schemas"]["StateDiff"] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[tuple[PrCheckSummary, ...], NotAvailable]] */
        Envelope_Union_tuple_PrCheckSummary___________NotAvailable__: {
            /** Data */
            data: components["schemas"]["PrCheckSummary"][] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /** Envelope[Union[tuple[StepView, ...], NotAvailable]] */
        Envelope_Union_tuple_StepView___________NotAvailable__: {
            /** Data */
            data: components["schemas"]["StepView"][] | components["schemas"]["NotAvailable"] | null;
            error: components["schemas"]["ErrorInfo"] | null;
            meta: components["schemas"]["ResponseMeta"];
            /** Success */
            success: boolean;
        };
        /**
         * ErrorInfo
         * @description Machine-readable error detail. Never carries a path or secret.
         */
        ErrorInfo: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * EstimatorConfig
         * @description The sampling plan that produced this blame result, taken verbatim from
         *     the `attribution.estimate.SequentialConfig` instance actually used --
         *     never hand-typed -- so a client (e.g. the Run detail page) never has to
         *     hard-code delta or any other threshold.
         */
        EstimatorConfig: {
            /** Batch */
            batch: number;
            /** Conf */
            conf: number;
            /**
             * Control Mode
             * @enum {string}
             */
            control_mode: "shared" | "per_step";
            /** Delta */
            delta: number;
            /**
             * Efficacy Boundary
             * @enum {string}
             */
            efficacy_boundary: "obf" | "none";
            /** Max N */
            max_n: number;
            /** Shortlist M */
            shortlist_m: number;
        };
        /** FlakyAblation */
        FlakyAblation: {
            /** Arms */
            arms: [
                components["schemas"]["AblationArm"],
                components["schemas"]["AblationArm"]
            ];
            difference: components["schemas"]["CiValue"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HeadlineResult
         * @description Bisect vs. the best judge, each with its own 95% CI, plus the gap
         *     between them with its own paired-bootstrap CI (never a Newcombe interval
         *     over the two accuracies -- they're measured on the same dataset).
         */
        HeadlineResult: {
            best_judge: components["schemas"]["CiValue"];
            /**
             * Best Judge Method
             * @enum {string}
             */
            best_judge_method: "bisect" | "judge_all_at_once" | "judge_step_by_step" | "rerun_live" | "no_control";
            bisect: components["schemas"]["CiValue"];
            gap: components["schemas"]["CiValue"];
        };
        /** HealthPayload */
        HealthPayload: {
            /** Status */
            status: string;
        };
        /** HeatmapCell */
        HeatmapCell: {
            /** Accuracy */
            accuracy: number;
            /**
             * Fault Type
             * @enum {string}
             */
            fault_type: "wrong_value" | "missing_field" | "stale_record" | "tool_error";
            /**
             * Method
             * @enum {string}
             */
            method: "bisect" | "judge_all_at_once" | "judge_step_by_step" | "rerun_live" | "no_control";
            /** N */
            n: number;
        };
        /** InterventionDiff */
        InterventionDiff: {
            /** Original Tool Result */
            original_tool_result: {
                [key: string]: string;
            };
            /** Replaced Tool Result */
            replaced_tool_result: {
                [key: string]: string;
            };
            /** Step Idx */
            step_idx: number;
        };
        /**
         * JobStatus
         * @description A long-running job's status. `state` and `progress`/`started_at`/
         *     `finished_at`/`error` must agree -- a job can't be "queued" with 77%
         *     progress, or "done" without a `finished_at` -- enforced below rather
         *     than left to whoever constructs one (the fixture simulator, or a
         *     parsed real-mode `runs/<phase>/status.json`) to get right by hand.
         *
         *     Every field past `state` is optional/nullable: fixture mode always
         *     fills what a real job of that kind plausibly would; real mode reports
         *     exactly what the job's own status file says, `None` for anything it
         *     doesn't -- never invented.
         */
        JobStatus: {
            /** Calls Spent */
            calls_spent?: number | null;
            /** Error */
            error?: string | null;
            /** Eta Seconds */
            eta_seconds?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Items Done */
            items_done?: number | null;
            /** Items Total */
            items_total?: number | null;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            /** Label */
            label?: string | null;
            /** Last Checkpoint At */
            last_checkpoint_at?: string | null;
            /** Model */
            model?: string | null;
            /** Phase */
            phase?: string | null;
            /** Progress */
            progress: number;
            /** Started At */
            started_at?: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "failed";
        };
        /** JudgePanel */
        JudgePanel: {
            /** All At Once */
            all_at_once: components["schemas"]["JudgeRankEntry"][];
            /** Step By Step */
            step_by_step: components["schemas"]["JudgeRankEntry"][];
        };
        /** JudgeRankEntry */
        JudgeRankEntry: {
            /** Rank */
            rank: number;
            /** Rationale */
            rationale: string;
            /** Score */
            score: number;
            /** Step */
            step: number;
        };
        /** Kpis */
        Kpis: {
            /** Calls Spent */
            calls_spent: number;
            /** Cost Per Diagnosis Usd */
            cost_per_diagnosis_usd: number;
            /** Failures Diagnosed */
            failures_diagnosed: number;
            /** Runs Recorded */
            runs_recorded: number;
        };
        /** LiveEvent */
        LiveEvent: {
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warn" | "error";
            /** Message */
            message: string;
            /** Ts */
            ts: string;
        };
        /** LiveSnapshot */
        LiveSnapshot: {
            budget: components["schemas"]["BudgetStatus"];
            /** Calls Series */
            calls_series: components["schemas"]["CallsPoint"][];
            /** Events */
            events: components["schemas"]["LiveEvent"][];
            /** Jobs */
            jobs: components["schemas"]["JobStatus"][];
            rate_limit: components["schemas"]["RateLimitStatus"];
        };
        /**
         * MetaPayload
         * @description `/api/meta`: what data backs this server process, and what built it.
         */
        MetaPayload: {
            /** Agent Model */
            agent_model: string;
            /**
             * Data Source
             * @enum {string}
             */
            data_source: "fixture" | "real";
            /** Generated At */
            generated_at: string;
            /** Package Version */
            package_version: string;
            /** Simulated */
            simulated: boolean;
            /** Tau2 Commit */
            tau2_commit: string;
            /** User Model */
            user_model: string;
        };
        /** MethodResult */
        MethodResult: {
            accuracy: components["schemas"]["CiValue"];
            /** Mean Calls */
            mean_calls: number;
            /** Mean Cost Usd */
            mean_cost_usd: number;
            /**
             * Method
             * @enum {string}
             */
            method: "bisect" | "judge_all_at_once" | "judge_step_by_step" | "rerun_live" | "no_control";
        };
        /**
         * NotAvailable
         * @description A typed placeholder for data `real_repository` cannot yet serve.
         *
         *     Never a stand-in for a real number: any endpoint returning this must
         *     never also invent a plausible-looking value for the same field.
         */
        NotAvailable: {
            /** Reason */
            reason: string;
            /**
             * Status
             * @default not_available
             */
            status: string;
        };
        /** OverviewPayload */
        OverviewPayload: {
            /** Cost Vs Accuracy */
            cost_vs_accuracy: components["schemas"]["CostAccuracyPoint"][];
            headline: components["schemas"]["HeadlineResult"];
            hero_run: components["schemas"]["RunSummary"];
            kpis: components["schemas"]["Kpis"];
            /** Recall At M */
            recall_at_m: components["schemas"]["RecallPoint"][];
        };
        /** PositionAccuracy */
        PositionAccuracy: {
            /** Accuracy */
            accuracy: number;
            /**
             * Method
             * @enum {string}
             */
            method: "bisect" | "judge_all_at_once" | "judge_step_by_step" | "rerun_live" | "no_control";
            /** N */
            n: number;
            /**
             * Position
             * @enum {string}
             */
            position: "early" | "middle" | "late";
        };
        /** PrCheckDetail */
        PrCheckDetail: {
            base_pass_rate: components["schemas"]["CiValue"];
            /** Check Id */
            check_id: string;
            /** Comment Markdown */
            comment_markdown: string;
            /** Decisive Step Base */
            decisive_step_base: number | null;
            /** Decisive Step Head */
            decisive_step_head: number | null;
            head_pass_rate: components["schemas"]["CiValue"];
            /** Is Regression */
            is_regression: boolean;
            /** P Value */
            p_value: number;
            /** Pr Number */
            pr_number: number;
            /** Scenarios */
            scenarios: components["schemas"]["ScenarioRow"][];
            /** Title */
            title: string;
        };
        /** PrCheckSummary */
        PrCheckSummary: {
            /** Base Pass Rate */
            base_pass_rate: number;
            /** Check Id */
            check_id: string;
            /** Head Pass Rate */
            head_pass_rate: number;
            /** Is Regression */
            is_regression: boolean;
            /** P Value */
            p_value: number;
            /** Pr Number */
            pr_number: number;
            /** Title */
            title: string;
        };
        /** RateLimitStatus */
        RateLimitStatus: {
            /** Current Rpm */
            current_rpm: number;
            /** Headroom Rpm */
            headroom_rpm: number;
            /** Limiter Rpm */
            limiter_rpm: number;
        };
        /** RecallPoint */
        RecallPoint: {
            /** M */
            m: number;
            /** Recall */
            recall: number;
        };
        /** RerunPage */
        RerunPage: {
            /** Reruns */
            reruns: components["schemas"]["RerunRow"][];
        };
        /**
         * RerunRow
         * @description One individual treated/control re-run in the matrix.
         */
        RerunRow: {
            /**
             * Arm
             * @enum {string}
             */
            arm: "treated" | "control";
            /** Calls */
            calls: number;
            /** N Steps */
            n_steps: number;
            /** Passed */
            passed: boolean;
            /** Rerun Id */
            rerun_id: string;
            /** Seed */
            seed: number;
            /** Step */
            step: number;
        };
        /**
         * ResponseMeta
         * @description Envelope metadata. `simulated` is `True` for every fixture-backed response.
         */
        ResponseMeta: {
            /**
             * Data Source
             * @enum {string}
             */
            data_source: "fixture" | "real";
            /** Limit */
            limit?: number | null;
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page */
            page?: number | null;
            /** Simulated */
            simulated: boolean;
            /** Total */
            total?: number | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Agent Model */
            agent_model: string;
            /** Created At */
            created_at: string;
            /** Domain */
            domain: string;
            estimate: components["schemas"]["RunEstimateView"] | null;
            /** Fault Type */
            fault_type: ("wrong_value" | "missing_field" | "stale_record" | "tool_error") | null;
            judge: components["schemas"]["JudgePanel"] | null;
            /** Outcome */
            outcome: ("pass" | "fail") | null;
            /** Planted Step */
            planted_step: number | null;
            /** Reward */
            reward: number | null;
            /** Run Id */
            run_id: string;
            /** Seed */
            seed: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "recording" | "complete";
            /** Steps */
            steps: components["schemas"]["StepView"][];
            /** Task Id */
            task_id: string;
            /** Tau2 Commit */
            tau2_commit: string;
            /** User Model */
            user_model: string;
        };
        /**
         * RunEstimateView
         * @description DTO for `attribution.estimate.RunEstimate`.
         */
        RunEstimateView: {
            /** Blamed Step */
            blamed_step: number | null;
            config: components["schemas"]["EstimatorConfig"];
            /** Control Fork Step */
            control_fork_step: number | null;
            /**
             * Control Mode
             * @enum {string}
             */
            control_mode: "shared" | "per_step" | "none";
            /** Control Reruns */
            control_reruns: number;
            /** Sampler Calls */
            sampler_calls: number;
            /** Step Effects */
            step_effects: components["schemas"]["StepEffectView"][];
            /** Treated Reruns */
            treated_reruns: number;
        };
        /** RunListPage */
        RunListPage: {
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /** RunSummary */
        RunSummary: {
            /** Blame Stripe */
            blame_stripe: components["schemas"]["BlameCell"][];
            /** Calls */
            calls: number | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Decisive Step */
            decisive_step: number | null;
            /** Domain */
            domain: string;
            /** Fault Type */
            fault_type: ("wrong_value" | "missing_field" | "stale_record" | "tool_error") | null;
            /** Model */
            model: string;
            /** N Steps */
            n_steps: number;
            /** Outcome */
            outcome: ("pass" | "fail") | null;
            /** Planted Step */
            planted_step: number | null;
            /** Run Id */
            run_id: string;
            /** Sparkline */
            sparkline: components["schemas"]["SparkPoint"][];
            /**
             * Status
             * @enum {string}
             */
            status: "recording" | "complete";
            /** Task Id */
            task_id: string;
        };
        /** SankeyFlow */
        SankeyFlow: {
            /** Count */
            count: number;
            /**
             * Fault Type
             * @enum {string}
             */
            fault_type: "wrong_value" | "missing_field" | "stale_record" | "tool_error";
            /**
             * Label
             * @enum {string}
             */
            label: "exact" | "earlier" | "later" | "none";
        };
        /** ScenarioRow */
        ScenarioRow: {
            /** Base Pass Rate */
            base_pass_rate: number;
            /** Head Pass Rate */
            head_pass_rate: number;
            /** N */
            n: number;
            /** Scenario */
            scenario: string;
        };
        /** SearchHit */
        SearchHit: {
            /** Href */
            href: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status?: ("recording" | "complete") | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title: string;
        };
        /** SearchResults */
        SearchResults: {
            /** Hits */
            hits: components["schemas"]["SearchHit"][];
            /** Query */
            query: string;
        };
        /** SparkPoint */
        SparkPoint: {
            /**
             * Actor
             * @enum {string}
             */
            actor: "agent" | "user" | "tool" | "evaluator";
            /** Latency Ms */
            latency_ms: number | null;
            /** Step Idx */
            step_idx: number;
            /** Tokens */
            tokens: number | null;
        };
        /** StateDiff */
        StateDiff: {
            /** Entries */
            entries: components["schemas"]["DiffEntry"][];
            /** Step Idx */
            step_idx: number;
        };
        /**
         * StepEffectView
         * @description DTO for `attribution.estimate.StepEffect`.
         */
        StepEffectView: {
            /** Ci High */
            ci_high: number;
            /** Ci Low */
            ci_low: number;
            control: components["schemas"]["ArmResultView"] | null;
            /** Effect */
            effect: number;
            /** N Batches */
            n_batches: number;
            /** Step */
            step: number;
            /**
             * Stop Reason
             * @enum {string}
             */
            stop_reason: "blameworthy" | "cleared" | "max_n";
            treated: components["schemas"]["ArmResultView"];
        };
        /**
         * StepPayload
         * @description The step inspector's detail for one step: messages plus tool call/result.
         */
        StepPayload: {
            /** Messages */
            messages: {
                [key: string]: string;
            }[];
            /** Step Idx */
            step_idx: number;
            /** Tool Args */
            tool_args: {
                [key: string]: string;
            } | null;
            /** Tool Result */
            tool_result: {
                [key: string]: string;
            } | null;
        };
        /** StepView */
        StepView: {
            /**
             * Actor
             * @enum {string}
             */
            actor: "agent" | "user" | "tool" | "evaluator";
            /** From Tape */
            from_tape: boolean;
            /** State Changed */
            state_changed: boolean;
            /** Step Idx */
            step_idx: number;
            /** Text */
            text: string;
            /** Tool Name */
            tool_name: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_benchmark_api_benchmark_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_BenchmarkSummary__NotAvailable__"];
                };
            };
        };
    };
    get_dataset_api_dataset_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_DatasetPage__NotAvailable__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthPayload_"];
                };
            };
        };
    };
    get_live_snapshot_api_live_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_LiveSnapshot__NotAvailable__"];
                };
            };
        };
    };
    stream_live_api_live_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_MetaPayload_"];
                };
            };
        };
    };
    get_overview_api_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_OverviewPayload__NotAvailable__"];
                };
            };
        };
    };
    list_pr_checks_api_pr_checks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_tuple_PrCheckSummary___________NotAvailable__"];
                };
            };
        };
    };
    get_pr_check_detail_api_pr_checks__check_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                check_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_PrCheckDetail__NotAvailable__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                domain?: string | null;
                outcome?: string | null;
                status?: string | null;
                model?: string | null;
                fault_type?: string | null;
                q?: string | null;
                sort?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_RunListPage__NotAvailable__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_detail_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RunDetail_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reruns_api_runs__run_id__reruns_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_RerunPage__NotAvailable__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rerun_steps_api_runs__run_id__reruns__rerun_id__steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                rerun_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_tuple_StepView___________NotAvailable__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_step_payload_api_runs__run_id__steps__step_idx__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                step_idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_StepPayload_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_intervention_diff_api_runs__run_id__steps__step_idx__intervention_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                step_idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_InterventionDiff__NoneType__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_diff_api_runs__run_id__steps__step_idx__state_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                step_idx: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Union_StateDiff__NotAvailable__"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SearchResults_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
