"""Tests for agent_bisect.core.models: reading the chosen models.

`config/models.toml` is generated by `scripts/decide_models.py` from the P0
measurements. Nothing downstream may hard-code a model id, so this reader
is the one place the choice enters the code.
"""

from __future__ import annotations

import pytest
from agent_bisect.core.models import (
    ChosenModels,
    MissingModelsConfigError,
    load_chosen_models,
)

_TOML = """
date = "2026-09-17"
tau2_commit = "2174a603f6d014ef94473ffa95957f6ce27100db"
agent = "nvidia/nemotron-3-super-120b-a12b"
user_sim = "nvidia/nemotron-3.5-lightning-30b-a3b"
judge = "nvidia/nemotron-3-ultra-550b-a55b"
airline_pass_rate = 0.6

[temperatures]
agent = 0.0
user = 0.25
"""


@pytest.fixture
def config(tmp_path):
    path = tmp_path / "models.toml"
    path.write_text(_TOML)
    return path


def test_reads_the_three_chosen_models(config):
    chosen = load_chosen_models(config)

    assert chosen.agent == "nvidia/nemotron-3-super-120b-a12b"
    assert chosen.user_sim == "nvidia/nemotron-3.5-lightning-30b-a3b"
    assert chosen.judge == "nvidia/nemotron-3-ultra-550b-a55b"


def test_reads_the_pinned_temperatures(config):
    chosen = load_chosen_models(config)

    assert chosen.agent_temperature == 0.0
    assert chosen.user_temperature == 0.25


def test_reads_the_pinned_tau2_commit(config):
    assert load_chosen_models(config).tau2_commit.startswith("2174a603")


def test_is_frozen(config):
    chosen = load_chosen_models(config)

    with pytest.raises(Exception):  # noqa: B017 - pydantic raises its own type
        chosen.agent = "something-else"  # pyright: ignore[reportAttributeAccessIssue]


def test_temperatures_default_to_zero_when_the_section_is_absent(tmp_path):
    path = tmp_path / "models.toml"
    path.write_text('agent = "a"\nuser_sim = "u"\njudge = "j"\ntau2_commit = "c"\n')

    chosen = load_chosen_models(path)

    assert (chosen.agent_temperature, chosen.user_temperature) == (0.0, 0.0)


def test_a_missing_file_is_a_loud_error(tmp_path):
    """Falling back to a hard-coded model would silently un-pin the study."""
    with pytest.raises(MissingModelsConfigError, match="decide_models"):
        load_chosen_models(tmp_path / "absent.toml")


def test_a_config_missing_a_model_is_a_loud_error(tmp_path):
    path = tmp_path / "models.toml"
    path.write_text('agent = "a"\ntau2_commit = "c"\n')

    with pytest.raises(MissingModelsConfigError, match="user_sim"):
        load_chosen_models(path)


def test_the_repos_own_config_is_readable_and_pins_all_three():
    """The generated file this study actually runs on."""
    chosen = load_chosen_models()

    assert isinstance(chosen, ChosenModels)
    assert chosen.agent and chosen.user_sim and chosen.judge
    assert len(chosen.tau2_commit) == 40
