"""Turning a gate's criteria into its evidence document.

`docs/gates/Pn.md` is generated from the very criteria the gate just
evaluated, so its numbers cannot drift from the numbers that produced the
verdict — retyping them is how an evidence file comes to disagree with
the run it claims to describe.

`scripts/gates/p0.py` grew its own copy of `current_commit` and
`last_commit_for` before this module existed; they are the same two
functions and p0's gate could adopt these when it is next touched.
"""

from __future__ import annotations

import subprocess
from collections.abc import Iterable, Mapping, Sequence
from typing import Protocol

REPO_ROOT_MARKER = "pyproject.toml"


class Criterion(Protocol):
    """The shape every gate's criterion has."""

    name: str
    passed: bool
    detail: str


def _repo_root() -> str:
    from pathlib import Path

    here = Path(__file__).resolve()
    for parent in here.parents:
        if (parent / REPO_ROOT_MARKER).exists():
            return str(parent)
    return str(here.parent)


def _git(*args: str) -> str:
    completed = subprocess.run(  # noqa: S603 - fixed, non-shell argv
        ["git", *args], capture_output=True, text=True, cwd=_repo_root()
    )
    return completed.stdout.strip()


def current_commit() -> str:
    """Repository HEAD, short. See the provenance note in `format_evidence`."""
    return _git("rev-parse", "--short", "HEAD") or "unknown"


def last_commit_for(path: str) -> str:
    """The commit that last touched `path`, or "uncommitted"."""
    return _git("log", "-1", "--format=%h %s", "--", path) or "uncommitted"


def provenance_for(paths: Iterable[str]) -> dict[str, str]:
    return {path: last_commit_for(path) for path in paths}


def render_table(header: Sequence[str], rows: Sequence[Sequence[str]]) -> str:
    """A markdown table, or a line saying there is nothing to show."""
    if not rows:
        return "_none_"
    lines = [
        "| " + " | ".join(header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]
    lines.extend("| " + " | ".join(str(cell) for cell in row) + " |" for row in rows)
    return "\n".join(lines)


def _verdict(criteria: Sequence[Criterion]) -> str:
    return "PASS" if all(criterion.passed for criterion in criteria) else "FAILED"


def format_evidence(
    *,
    gate: str,
    title: str,
    script: str,
    criteria: Sequence[Criterion],
    gate_text: str,
    commands: Sequence[str],
    provenance: Mapping[str, str],
    sections: Mapping[str, str],
    commit: str,
) -> str:
    """The whole document, as text."""
    criteria_table = render_table(
        ("Criterion", "Result", "Detail"),
        [
            (f"`{criterion.name}`", "PASS" if criterion.passed else "FAILED", criterion.detail)
            for criterion in criteria
        ],
    )
    provenance_table = render_table(
        ("File", "Commit"), [(f"`{path}`", value) for path, value in provenance.items()]
    )
    parts = [
        f"# {gate} gate — {title}",
        "",
        f"**Verdict: {_verdict(criteria)}** at commit `{commit}`.",
        "",
        f"Generated by `{script} --write-evidence`; re-running it reproduces this file "
        "from the store it just checked.",
        "",
        "## Provenance",
        "",
        "The commit above is repository HEAD when this ran; in a shared tree that can be an "
        "unrelated change. These are the commits that actually produced the verdict:",
        "",
        provenance_table,
        "",
        "## Gate (pre-registered in docs/decisions/0001-preregistration.md)",
        "",
        f"> {gate_text}",
        "",
        "## Commands",
        "",
        "```",
        *commands,
        "```",
        "",
        "## Criteria",
        "",
        criteria_table,
    ]
    for heading, body in sections.items():
        parts.extend(["", f"## {heading}", "", body])
    return "\n".join(parts) + "\n"
